### ISSUE TITLE
Database model

### ISSUE THREAD

**Issue by zuntrax** [uni-kult/accounting#1]
![img_20150309_174145](https://cloud.githubusercontent.com/assets/6196356/6561160/596dbede-c68f-11e4-9ac0-741a08db4e84.jpg)
![img_20150309_174150](https://cloud.githubusercontent.com/assets/6196356/6561161/5973b316-c68f-11e4-89ba-c0fa66f9511d.jpg)

**Comment by lukaslentner** [comment]
Habs ins Wiki gepackt mit einer Auflistung aller Eigenschaften die mir so in den Sinn kamen. [Wiki Seite](https://github.com/uni-kult/accounting/wiki/Model)
